<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY93uEYS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY93uEYS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY93uEYS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY93uEYS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY93uEYS\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y93uEYS',
    'container.build_id' => 'f5b13a59',
    'container.build_time' => 1613601976,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY93uEYS');
