<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTylVnpN\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTylVnpN/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerTylVnpN.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerTylVnpN\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerTylVnpN\App_KernelTestDebugContainer([
    'container.build_hash' => 'TylVnpN',
    'container.build_id' => 'e9d0f7a0',
    'container.build_time' => 1613602058,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTylVnpN');
